# Generated by Django 4.1.7 on 2023-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_acessório_cor_veículo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veículo',
            name='modelo',
            field=models.CharField(default='', max_length=150),
        ),
    ]
