# Generated by Django 4.1.7 on 2023-03-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_alter_cor_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acessório',
            new_name='acessorio',
        ),
        migrations.RenameModel(
            old_name='Veículo',
            new_name='veiculo',
        ),
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'Acessório'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo'},
        ),
    ]
