# Generated by Django 4.1.7 on 2023-03-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0006_rename_acessório_acessorio_rename_veículo_veiculo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acessorio',
            new_name='acessorios',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={},
        ),
    ]
