# Generated by Django 4.1.7 on 2023-04-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0008_rename_acessorios_acessorio_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'acessório'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria'},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'marca'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'veículo'},
        ),
    ]
