# Generated by Django 4.2.4 on 2023-08-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0009_alter_acessorio_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'Acessório'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca'},
        ),
    ]
