# Generated by Django 4.2.4 on 2023-08-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0011_remove_veiculo_categoria_remove_veiculo_marca_modelo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name': 'Modelo'},
        ),
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='garagem.categoria'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='garagem.marca'),
        ),
    ]
