# Generated by Django 4.2.4 on 2023-08-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0012_alter_modelo_options_alter_modelo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(default='', max_length=500),
        ),
    ]
