# Generated by Django 4.2.4 on 2023-08-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0013_veiculo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(related_name='veiculos', to='garagem.acessorio'),
        ),
    ]
